http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  validator:
    host: localhost
    paths: ["/validateNumber", "/validateNumber/*"]
  customer:
    host: localhost
    paths: ["/customers", "/customers/*"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  validatorService:
    url: "http://localhost:4000"
  customerService:
    url: "http://localhost:8000"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - validator
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: validatorService
              changeOrigin: true
  musicPipeline:
    apiEndpoints:
      - customer
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: customerService
              changeOrigin: true
